[package]
name = "server"
version = "0.1.0"
authors = ["vulfke482 <denis.kartashov@482.solutions>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb="0.13.0"
bytes="0.5"
threadpool="1.7.1"
rand="0.7.2"