[package]
name = "client"
version = "0.1.0"
authors = ["vulfke482 <denis.kartashov@482.solutions>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
